#!/usr/bin/env python3
"""
generate_map.py — Generate the Stage A occupancy grid map for Nav2.

The map must match the stage_a.sdf Gazebo world exactly.
Run this script whenever you change wall/obstacle positions in the SDF.

Output files (written next to this script):
    stage_a.pgm   — PGM P2 (ASCII) grayscale image, 200×200 pixels
    stage_a.yaml  — Nav2 map_server YAML (already committed, but regenerated)

Map specification:
    Size        : 20 m × 20 m
    Resolution  : 0.10 m / pixel  →  200 × 200 pixels
    Origin      : (-10.0, -10.0, 0.0)  (bottom-left world corner)
    Free        : 255 (white)
    Occupied    : 0   (black)

Pixel ↔ world conversion:
    col = int((world_x - ORIGIN_X) / RESOLUTION)
    row = int((world_y - ORIGIN_Y) / RESOLUTION)
    (row 0 = south edge, row 199 = north edge in the internal array;
     PGM is written top-to-bottom so the array is vertically flipped when output.)
"""

import os

# ── Map parameters (must match stage_a.sdf) ──────────────────────────────
WIDTH      = 200       # pixels  (20 m / 0.10 m)
HEIGHT     = 200       # pixels
RESOLUTION = 0.10      # m/pixel
ORIGIN_X   = -10.0     # world X of left edge
ORIGIN_Y   = -10.0     # world Y of bottom edge

FREE     = 254   # Nav2 free threshold > 0.196 → any value ≥ 50 is fine
OCCUPIED = 0

# Extra padding added to obstacle extents to match the costmap inflation
# (set to 0 here — inflation is handled by Nav2's InflationLayer)
PADDING = 0


def world_to_pixel(wx, wy):
    """Convert world (m) centre to pixel (col, row) in the internal array."""
    col = int((wx - ORIGIN_X) / RESOLUTION)
    row = int((wy - ORIGIN_Y) / RESOLUTION)
    return col, row


def fill_rect_world(img, wx_c, wy_c, wx_size, wy_size, value, pad=0):
    """Fill a rectangle specified in world coordinates (centre + half-sizes)."""
    col_min = int((wx_c - wx_size / 2 - pad - ORIGIN_X) / RESOLUTION)
    col_max = int((wx_c + wx_size / 2 + pad - ORIGIN_X) / RESOLUTION) + 1
    row_min = int((wy_c - wy_size / 2 - pad - ORIGIN_Y) / RESOLUTION)
    row_max = int((wy_c + wy_size / 2 + pad - ORIGIN_Y) / RESOLUTION) + 1
    for r in range(max(0, row_min), min(HEIGHT, row_max)):
        for c in range(max(0, col_min), min(WIDTH, col_max)):
            img[r][c] = value


def main():
    # Internal image: img[row][col], row 0 = south (y=-10), row 199 = north
    img = [[FREE] * WIDTH for _ in range(HEIGHT)]

    # ── Boundary walls ────────────────────────────────────────────────────
    # Wall thickness in world: 0.30 m  →  3 pixels
    WALL_W = 0.30

    # West wall: centred at x = -9.85 (world)
    fill_rect_world(img, -9.85, 0.0,  WALL_W, 20.0, OCCUPIED)
    # East wall
    fill_rect_world(img,  9.85, 0.0,  WALL_W, 20.0, OCCUPIED)
    # South wall (fits between west/east walls in SDF: size 19.4 × 0.3)
    fill_rect_world(img,  0.0, -9.85, 19.40, WALL_W, OCCUPIED)
    # North wall
    fill_rect_world(img,  0.0,  9.85, 19.40, WALL_W, OCCUPIED)

    # ── Interior obstacles (must match stage_a.sdf exactly) ───────────────
    # OBS-1  1×1 m at (4, 4)
    fill_rect_world(img,  4.0,  4.0,  1.0, 1.0, OCCUPIED)
    # OBS-2  1×1 m at (-4, 4)
    fill_rect_world(img, -4.0,  4.0,  1.0, 1.0, OCCUPIED)
    # OBS-3  1×1 m at (4, -4)
    fill_rect_world(img,  4.0, -4.0,  1.0, 1.0, OCCUPIED)
    # OBS-4  1×1 m at (-4, -4)
    fill_rect_world(img, -4.0, -4.0,  1.0, 1.0, OCCUPIED)
    # OBS-5  1×2 m at (4.0, 3.0), outside the spawn corridor
    fill_rect_world(img,  4.0,  3.0,  1.0, 2.0, OCCUPIED)
    # OBS-6  1×1 m at (-2, -2)
    fill_rect_world(img, -2.0, -2.0,  1.0, 1.0, OCCUPIED)
    # OBS-7  3×0.3 m at (0, 5)
    fill_rect_world(img,  0.0,  5.0,  3.0, 0.3, OCCUPIED)

    # Stage A disaster-terrain additions. These are marked occupied because
    # the 2-D Nav2 map cannot yet model slope traversability.
    # RAMP-1  2.4×1.2 m at (-5.8, 0.5)
    fill_rect_world(img, -5.8,  0.5,  2.4, 1.2, OCCUPIED)
    # RAMP-2  rotated 2.2×1.1 m at (6.0, -2.5), conservative 2-D bounds
    fill_rect_world(img,  6.0, -2.5,  1.1, 2.2, OCCUPIED)
    # RUB-1/RUB-2  west-side clutter, conservative bounds for yawed boxes
    fill_rect_world(img, -5.5,  2.2,  1.3, 0.8, OCCUPIED)
    fill_rect_world(img, -6.2,  1.4,  1.0, 0.9, OCCUPIED)
    # RUB-3  angled debris wall, conservative bounds
    fill_rect_world(img,  1.0, -5.8,  2.7, 1.4, OCCUPIED)
    # RUB-4  small debris cube
    fill_rect_world(img,  5.8,  2.1,  0.9, 0.9, OCCUPIED)

    # ── Write PGM (P2 ASCII format) ───────────────────────────────────────
    # PGM row 0 = top of image = north edge of world (row HEIGHT-1 in img array)
    out_dir  = os.path.dirname(os.path.abspath(__file__))
    pgm_path = os.path.join(out_dir, 'stage_a.pgm')

    with open(pgm_path, 'w') as f:
        f.write('P2\n')
        f.write('# Stage A navigation map — auto-generated by generate_map.py\n')
        f.write(f'{WIDTH} {HEIGHT}\n')
        f.write('255\n')
        # Write rows from top (north, high row index) to bottom (south, row 0)
        for row in range(HEIGHT - 1, -1, -1):
            f.write(' '.join(str(img[row][col]) for col in range(WIDTH)))
            f.write('\n')

    print(f'[generate_map] Wrote {pgm_path}  ({WIDTH}×{HEIGHT} @ {RESOLUTION} m/px)')


if __name__ == '__main__':
    main()
